# Generated by Django 2.2.6 on 2019-11-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('imgpath', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('logo', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Category')),
            ],
        ),
    ]
