# Generated by Django 2.2.6 on 2019-11-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=True)),
                ('name', models.CharField(choices=[(1, 'Languages'), (2, 'Cooking'), (3, 'Writing'), (4, 'Singing')], default=True, max_length=255)),
                ('img_path', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Phone'), (2, 'Facebook'), (3, 'Email')], default=True, max_length=90)),
                ('value', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('logo', models.CharField(default='', max_length=255)),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Branch')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Category')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Contact')),
            ],
        ),
    ]
